
DROP TABLE TABLE_OPN;
DROP TABLE TABLE_OPN_DETAIL;
DROP TABLE TABLE_OPN_DETAIL_TABLE;
DROP TABLE TABLE_OPN_DETAIL_TABLE_COLUMN;
DROP TABLE TABLE_RECRUITMENT_AREA;
DROP TABLE TABLE_PREFERENCE;
DROP TABLE TABLE_RECRUITMENT_INFO;
DROP TABLE TABLE_WORK_LOCATION;
DROP TABLE TABLE_OPN_FILES;

UPDATE TABLE_OPN SET IS_RECRUITING='T'  
WHERE OPN_NUM = 171 AND TO_DATE(OPN_RECRUIT_END)>SYSDATE AND SYSDATE>TO_DATE(OPN_RECRUIT_START);
UPDATE TABLE_OPN SET IS_RECRUITING='F'  
WHERE OPN_NUM = 171;

SELECT OPN_NUM, IS_RECRUITING, OPN_RECRUIT_END, SYSDATE FROM TABLE_OPN WHERE OPN_NUM=171;
SELECT * FROM TABLE_OPN to2;

SELECT tr.*,twl.WORK_LOCATION1,twl.WORK_LOCATION2,twl.WORK_LOCATION3 FROM(

SELECT * FROM TABLE_OPN WHERE OPN_COMP_ID='test1'
)tr, TABLE_WORK_LOCATION twl

WHERE tr.OPN_NUM = twl.OPN_NUM(+);

SELECT tr.*,twl.WORK_LOCATION1,twl.WORK_LOCATION2,twl.WORK_LOCATION3 FROM
	(SELECT * FROM (SELECT ROWNUM R, D.* FROM 
		(SELECT * FROM TABLE_OPN WHERE OPN_NUM IN (SELECT OPN_NUM FROM (SELECT * FROM TABLE_WORK_LOCATION) 
		INTERSECT    
		SELECT OPN_NUM FROM (SELECT * FROM TABLE_RECRUITMENT_AREA)))D)B
WHERE B.R BETWEEN 1 AND 5;

SELECT to2.*,twl.WORK_LOCATION1,twl.WORK_LOCATION2,twl.WORK_LOCATION3 FROM TABLE_OPN to2, TABLE_WORK_LOCATION twl 
WHERE to2.OPN_NUM = twl.OPN_NUM(+) AND to2.OPN_NUM=49;

SELECT tr.*,twl.WORK_LOCATION1,twl.WORK_LOCATION2,twl.WORK_LOCATION3 FROM(   SELECT * FROM TABLE_OPN WHERE OPN_COMP_ID='test2'   )tr, TABLE_WORK_LOCATION twlWHERE tr.OPN_NUM = twl.OPN_NUM(+);

INSERT INTO TABLE_OPN(OPN_NUM,OPN_COMP_ID,OPN_VIEWS, OPN_RECRUIT_START,OPN_RECRUIT_END)
VALUES(OPN_SEQ.NEXTVAL,'test1',32,TO_DATE('2021-01-12-00:00','YYYY-MM-DD-HH24:MI'),TO_DATE('2021-01-15-00:00','YYYY-MM-DD-HH24:MI'));

/* 공고 구분자 시퀀스 */
CREATE SEQUENCE OPN_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
CYCLE;

/* 모집부문 구분자 시퀀스 : PK는 조합키(공고 정보X모집부문 구분자) */
CREATE SEQUENCE RECRUITMENT_AREA_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
CYCLE;

/* 우대사항 구분자 시퀀스 : PK는 조합키(공고 정보X우대사항 구분자) */
CREATE SEQUENCE PREFERENCE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
CYCLE;


/* 상세정보 구분자 시퀀스 : PK는 조합키(공고 정보X상세정보 구분자) */
CREATE SEQUENCE OPN_DETAIL_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
CYCLE;

/* 상세정보 테이블 구분자 시퀀스 : PK는 조합키(공고 정보X테이블 구분자) */
CREATE SEQUENCE OPN_DETAIL_TABLE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
CYCLE;

/* 상세정보 테이블 로우 구분자 시퀀스  : PK는 조합키(공고 정보X테이블 구분자X로우 구분자) */
CREATE SEQUENCE OPN_DETAIL_TABLE_COLUMN_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
CYCLE;


/* 공고 테이블 */

CREATE TABLE TABLE_OPN(
	OPN_NUM NUMBER(3),
	OPN_COMP_ID VARCHAR2(100),
	OPN_VIEWS NUMBER(10) NOT NULL,
	OPN_TITLE VARCHAR2(200),
	OPN_CAREER VARCHAR2(200),
	OPN_EDU VARCHAR2(200),
	OPN_WORK_TYPE VARCHAR2(200),
	OPN_WORK_TIME VARCHAR2(200),
	OPN_SALARY VARCHAR2(200),
	OPN_RECRUIT_METHOD VARCHAR2(200) NOT NULL,
	OPN_RECRUIT_NAME VARCHAR2(200),
	OPN_RECRUIT_CONTACT VARCHAR2(200),
	OPN_WRITE_DATE DATE,
	OPN_RECRUIT_START DATE,
	OPN_RECRUIT_END DATE,
	OPN_URL VARCHAR2(3000),
	CONSTRAINT OPENING_FK FOREIGN KEY(OPN_COMP_ID) REFERENCES TABLE_COMP_USER(COMP_USER_ID),
	CONSTRAINT OPENING_PK PRIMARY KEY(OPN_NUM)
);
ALTER TABLE TABLE_OPN ADD IS_RECRUITING VARCHAR2(200);
ALTER TABLE TABLE_OPN DROP COLUMN IS_RECRUITING;

/* 채용 마감일이 지난 공고 번호 */
SELECT * FROM TABLE_OPN WHERE OPN_NUM IN (SELECT OPN_NUM FROM TABLE_OPN WHERE OPN_COMP_ID='test1') AND OPN_RECRUIT_END=NULL;  
SELECT * FROM TABLE_OPN WHERE OPN_NUM=76;
SELECT COUNT(*) FROM TABLE_OPN WHERE OPN_COMP_ID='test1' AND IS_RECRUITING='T';




DELETE FROM TABLE_RECRUITMENT_AREA WHERE OPN_NUM = 123;
DELETE FROM TABLE_PREFERENCE WHERE OPN_NUM = 123;
DELETE FROM TABLE_RECRUITMENT_INFO WHERE OPN_NUM = 123;
DELETE FROM TABLE_WORK_LOCATION WHERE OPN_NUM = 123;
DELETE FROM TABLE_OPN_DETAIL WHERE OPN_NUM = 123;
DELETE FROM TABLE_OPN_DETAIL_TABLE WHERE OPN_NUM = 123;
DELETE FROM TABLE_OPN_DETAIL_TABLE_COLUMN WHERE OPN_NUM = 123;
DELETE FROM TABLE_OPN_FILES WHERE OPN_NUM = 123;
DELETE FROM TABLE_OPN  WHERE OPN_NUM = 123;

SELECT * FROM 
	(SELECT ROWNUM R, D.* FROM 
		(SELECT * FROM TABLE_OPN WHERE OPN_NUM IN 
			(SELECT OPN_NUM FROM (SELECT * FROM TABLE_WORK_LOCATION)INTERSECT SELECT OPN_NUM FROM (SELECT * FROM TABLE_RECRUITMENT_AREA)WHERE OPN_TITLE LIKE '%공고%'))D)B
WHERE B.R BETWEEN 1 AND 5;



SELECT COUNT(*) FROM TABLE_OPN WHERE OPN_NUM IN      
	(SELECT OPN_NUM FROM (SELECT * FROM TABLE_WORK_LOCATION)INTERSECT SELECT OPN_NUM FROM (SELECT * FROM TABLE_RECRUITMENT_AREA)WHERE OPN_TITLE LIKE '%공고%');

SELECT * FROM TABLE_OPN WHERE OPN_NUM IN      
		(SELECT OPN_NUM FROM (SELECT * FROM TABLE_WORK_LOCATION)INTERSECT SELECT OPN_NUM FROM (SELECT * FROM TABLE_RECRUITMENT_AREA));

ALTER TABLE TABLE_OPN ADD(OPN_COMP_NAME VARCHAR2(200));




SELECT * FROM TABLE_OPN;
SELECT * FROM TABLE_RECRUITMENT_AREA;
SELECT * FROM TABLE_PREFERENCE;
SELECT * FROM TABLE_RECRUITMENT_INFO;
SELECT * FROM TABLE_OPN_DETAIL;
SELECT * FROM TABLE_OPN_DETAIL_TABLE;


/* 모집 부문 */
CREATE TABLE TABLE_RECRUITMENT_AREA(
	OPN_NUM NUMBER(3),
	RECRUITMENT_AREA_NUM NUMBER(3),
	RECRUITMENT_AREA VARCHAR2(200),
	CONSTRAINT RECRUITMENT_AREA_FK FOREIGN KEY(OPN_NUM) REFERENCES TABLE_OPN(OPN_NUM),
	CONSTRAINT RECRUITMENT_AREA_PK PRIMARY KEY(OPN_NUM,RECRUITMENT_AREA_NUM)
);
SELECT * FROM TABLE_RECRUITMENT_AREA;

INSERT INTO TABLE_RECRUITMENT_AREA(OPN_NUM,RECRUITMENT_AREA_NUM,RECRUITMENT_AREA)
VALUES(2,RECRUITMENT_AREA_SEQ.NEXTVAL,'모집분야1');
INSERT INTO TABLE_RECRUITMENT_AREA(OPN_NUM,RECRUITMENT_AREA_NUM,RECRUITMENT_AREA)
VALUES(2,RECRUITMENT_AREA_SEQ.NEXTVAL,'모집분야2');


/* 우대 사항 */
CREATE TABLE TABLE_PREFERENCE(
	OPN_NUM NUMBER(3),
	PREFERENCE_NUM NUMBER(3),
	PREFERENCE VARCHAR2(200),
	CONSTRAINT PREFERENCE_FK FOREIGN KEY(OPN_NUM) REFERENCES TABLE_OPN(OPN_NUM),
	CONSTRAINT PREFERENCE_PK PRIMARY KEY(OPN_NUM,PREFERENCE_NUM)
);
SELECT * FROM TABLE_PREFERENCE;

INSERT INTO TABLE_PREFERENCE (OPN_NUM,PREFERENCE_NUM,PREFERENCE)
VALUES(2,PREFERENCE_SEQ.NEXTVAL,'우대사항1');
INSERT INTO TABLE_PREFERENCE (OPN_NUM,PREFERENCE_NUM,PREFERENCE)
VALUES(2,PREFERENCE_SEQ.NEXTVAL,'우대사항2');

/* 채용 분야 */
CREATE TABLE TABLE_RECRUITMENT_INFO(
	OPN_NUM NUMBER(3),
	RECRUITMENT_INF1 VARCHAR2(200),
	RECRUITMENT_INF2 VARCHAR2(200),
	RECRUITMENT_INF3 VARCHAR2(200),
	CONSTRAINT RECRUITMENT_INFO_FK FOREIGN KEY(OPN_NUM) REFERENCES TABLE_OPN(OPN_NUM),
	CONSTRAINT RECRUITMENT_INFO_PK PRIMARY KEY(OPN_NUM)
);
SELECT * FROM TABLE_RECRUITMENT_INFO;

INSERT INTO TABLE_RECRUITMENT_INFO(OPN_NUM,RECRUITMENT_INF1,RECRUITMENT_INF2,RECRUITMENT_INF3)
VALUES(2,'채용 분야1','채용 분야2',NULL);

/* 근무 지역 */
CREATE TABLE TABLE_WORK_LOCATION(
	OPN_NUM NUMBER(3),
	WORK_LOCATION1 VARCHAR2(200),
	WORK_LOCATION2 VARCHAR2(200),
	WORK_LOCATION3 VARCHAR2(200),
	CONSTRAINT WORK_LOCATION_FK FOREIGN KEY(OPN_NUM) REFERENCES TABLE_OPN(OPN_NUM),
	CONSTRAINT WORK_LOCATION_PK PRIMARY KEY(OPN_NUM)
);
SELECT * FROM TABLE_WORK_LOCATION;

INSERT INTO TABLE_WORK_LOCATION(OPN_NUM,WORK_LOCATION1,WORK_LOCATION2,WORK_LOCATION3)
VALUES(2,'위치1','위치2','위치3');


/* 공고 정보에 포함할 상세정보 */
CREATE TABLE TABLE_OPN_DETAIL(
	OPN_NUM NUMBER(3),
	OPN_DETAIL_NUM NUMBER(10),
	OPN_DETAIL_TITLE VARCHAR2(200),
	OPN_DETAIL_CONTENT VARCHAR2(4000),
	CONSTRAINT OPN_DETAIL_FK FOREIGN KEY(OPN_NUM) REFERENCES TABLE_OPN(OPN_NUM),
	CONSTRAINT OPN_DETAIL_PK PRIMARY KEY(OPN_DETAIL_NUM,OPN_NUM)
);
SELECT * FROM TABLE_OPN_DETAIL;

INSERT INTO TABLE_OPN_DETAIL(OPN_NUM,OPN_DETAIL_NUM,OPN_DETAIL_TITLE,OPN_DETAIL_CONTENT)
VALUES(2,1,'상세정보 제목','상세정보 내용');

/* 공고 정보에 포함할 표 */
/* 상세 정보 테이블 한개는 두 개의 DB 테이블로 구성된다 */
/* 첫번째는 테이블의 정보 중 중복이 없는 정보(제목,정보 순서)이고 */
/* 두번째는 테이블의 정보 중 중복이 있는 정보(각 테이블의 열 내용)이다 */
/* 첫번째 테이블의 PK는 공고 번호와 테이블 번호로 이우러진 조합키이며, 두번째 테이블은 이 조합키를 FK로 사용한다 */
CREATE TABLE TABLE_OPN_DETAIL_TABLE(
	OPN_NUM NUMBER(3),
	OPN_DETAIL_TABLE_NUM NUMBER(3),
	OPN_DETAIL_TABLE_TITLE VARCHAR2(200),
	CONSTRAINT OPN_DETAIL_TABLE_FK FOREIGN KEY(OPN_NUM) REFERENCES TABLE_OPN(OPN_NUM),
	CONSTRAINT OPN_DETAIL_TABLE_PK PRIMARY KEY(OPN_DETAIL_TABLE_NUM,OPN_NUM)
);
CREATE TABLE TABLE_OPN_DETAIL_TABLE_COLUMN(
	OPN_NUM NUMBER(3),
	OPN_DETAIL_TABLE_NUM NUMBER(3),
	ROW_NUM NUMBER(10),
	COLUMN1 VARCHAR2(3000),
	COLUMN2 VARCHAR2(3000),
	CONSTRAINT OPN_DETAIL_TABLE_COLUMN_FK FOREIGN KEY(OPN_DETAIL_TABLE_NUM,OPN_NUM) REFERENCES TABLE_OPN_DETAIL_TABLE(OPN_DETAIL_TABLE_NUM,OPN_NUM),
	CONSTRAINT OPN_DETAIL_TABLE_COLUMN_PK PRIMARY KEY (ROW_NUM,OPN_DETAIL_TABLE_NUM,OPN_NUM)
);
/* 테이블 넘버 조회 메소드 */
SELECT * FROM (SELECT LAST_VALUE(OPN_DETAIL_TABLE_NUM) OVER() FROM TABLE_OPN_DETAIL_TABLE) WHERE ROWNUM=1;

SELECT * FROM TABLE_OPN_DETAIL_TABLE;
SELECT * FROM TABLE_OPN_DETAIL_TABLE_COLUMN;

INSERT INTO TABLE_OPN_DETAIL_TABLE (OPN_NUM,OPN_DETAIL_TABLE_NUM,OPN_DETAIL_TABLE_TITLE)
VALUES(2,1,'상세테이블 제목');
INSERT INTO TABLE_OPN_DETAIL_TABLE_COLUMN (OPN_NUM,OPN_DETAIL_TABLE_NUM,ROW_NUM,COLUMN1,COLUMN2)
VALUES(2,1,1,'모집부문','상세설명');
INSERT INTO TABLE_OPN_DETAIL_TABLE_COLUMN (OPN_NUM,OPN_DETAIL_TABLE_NUM,ROW_NUM,COLUMN1,COLUMN2)
VALUES(2,1,2,'모집부문 내용입니다','상세설명 내용입니다');
INSERT INTO TABLE_OPN_DETAIL_TABLE (OPN_NUM,OPN_DETAIL_TABLE_NUM,OPN_DETAIL_TABLE_TITLE)
VALUES(2,2,'상세테이블 제목2');
INSERT INTO TABLE_OPN_DETAIL_TABLE (OPN_NUM,OPN_DETAIL_TABLE_NUM,OPN_DETAIL_TABLE_TITLE)
VALUES(2,3,'상세테이블 제목2');

/* 공고 상세 내용 JOIN */
/* 공고 아이디(OPN_NUM)에 해당하는 상세 내용을 가져옴 */

SELECT topd.OPN_DETAIL_TITLE,topd.OPN_DETAIL_CONTENT
FROM TABLE_OPN_DETAIL topd
WHERE topd.OPN_NUM=21;

/* 공고 상세 내용 테이블 JOIN */
/* 공고 아이디(OPN_NUM)에 해당하는 상세 내용을 가져옴 */

SELECT topdt.OPN_DETAIL_TABLE_TITLE,topdt.OPN_DETAIL_TABLE_CONTENT
FROM TABLE_OPN_DETAIL_TABLE topdt
WHERE topdt.OPN_NUM=21;

/* 공고 첨부 파일 테이블 */
CREATE TABLE TABLE_OPN_FILES(
	OPN_NUM NUMBER(3),
	OPN_FILE_NAME VARCHAR2(100),
	CONSTRAINT OPN_FILES_FK FOREIGN KEY(OPN_NUM) REFERENCES TABLE_OPN(OPN_NUM),
	CONSTRAINT OPN_FILES_PK PRIMARY KEY(OPN_FILE_NAME)
);

SELECT * FROM TABLE_OPN_FILES;

