CREATE SEQUENCE BBS_REPLY_SEQ;

CREATE TABLE TABLE_BBS_REPLY(
	BBS_REPLY_NUM NUMBER(10),
	BBS_NUM NUMBER(10),
	USER_ID VARCHAR2(100),
	BBS_REPLY_CONTENT VARCHAR2(4000),
	CONSTRAINT BBS_REPLY_PK PRIMARY KEY(BBS_REPLY_NUM),
	CONSTRAINT BBS_REPLY_BBS_FK FOREIGN KEY(BBS_NUM) REFERENCES TABLE_BBS(BBS_NUM),
	CONSTRAINT BBS_REPLY_USER_FK FOREIGN KEY(USER_ID) REFERENCES TABLE_USER(USER_ID)
);

ALTER TABLE TABLE_BBS_REPLY DROP CONSTRAINT BBS_REPLY_BBS_FK;

/*부모가 삭제되면 자식도 삭제되도록 설정*/
/*ON DELETE CASCADE*/
ALTER TABLE TABLE_BBS_REPLY ADD CONSTRAINT REPLY_BBS_FK 
FOREIGN KEY(BBS_NUM) REFERENCES TABLE_BBS(BBS_NUM)
ON DELETE CASCADE;

SELECT * FROM TABLE_BBS_REPLY;
SELECT * FROM TABLE_BBS;

INSERT INTO TABLE_BBS_REPLY (BBS_REPLY_NUM, BBS_NUM, USER_ID, BBS_REPLY_CONTENT) 
VALUES (BBS_REPLY_SEQ.NEXTVAL, 42, 'wnsrbod', '댓글 테스트6');

DELETE FROM TABLE_BBS WHERE BBS_NUM = 41;
