--게시판 넘버 시퀀스
CREATE SEQUENCE REVIEW_NUM_SEQ;

--후기 게시판 테이블
CREATE TABLE TABLE_INTERVIEW_REVIEW_BOARD(
	USER_ID VARCHAR2(100),
	REVIEW_NUM NUMBER(10),
	REVIEW_WRTIE_DATE DATE,
	REVIEW_INTERVIEW_DATE VARCHAR2(100),
	REVIEW_COMPANY_NAME VARCHAR2(100),
	REVIEW_JOB VARCHAR2(100),
	REVIEW_CAREER VARCHAR2(100),
	REVIEW_LEVEL VARCHAR2(100),
	REVIEW_RESULT VARCHAR2(100),
	REVIEW_TYPE VARCHAR2(100),
	REVIEW_EVALUATION VARCHAR2(100),
	REVIEW_NUM_OF_PEOPLE VARCHAR2(100),
	REVIEW_REVIEW VARCHAR2(500),
	REVIEW_INTERVIEW_Q1 VARCHAR2(200),
	REVIEW_INTERVIEW_Q2 VARCHAR2(200),
	REVIEW_INTERVIEW_Q3 VARCHAR2(200),
	REVIEW_TIP VARCHAR2(500),	
	CONSTRAINT INTERVIEW_REVIEW_BOARD_PK PRIMARY KEY(REVIEW_NUM), 
	CONSTRAINT INTERVIEW_REVIEW_BOARD_FK FOREIGN KEY(USER_ID) REFERENCES TABLE_USER(USER_ID)
);

SELECT * FROM TABLE_INTERVIEW_REVIEW_BOARD WHERE REVIEW_CAREER = '신입';
DELETE FROM TABLE_INTERVIEW_REVIEW_BOARD WHERE REVIEW_COMPANY_NAME = '배달의 민족';


INSERT INTO HR.TABLE_INTERVIEW_REVIEW_BOARD
(USER_ID, REVIEW_NUM, REVIEW_WRTIE_DATE, REVIEW_INTERVIEW_DATE, REVIEW_COMPANY_NAME, REVIEW_JOB, REVIEW_CAREER, REVIEW_LEVEL, REVIEW_RESULT, REVIEW_TYPE, REVIEW_EVALUATION, REVIEW_NUM_OF_PEOPLE, REVIEW_REVIEW, REVIEW_INTERVIEW_Q1, REVIEW_INTERVIEW_Q2, REVIEW_INTERVIEW_Q3, REVIEW_TIP)
VALUES('korea1234', REVIEW_NUM_SEQ.NEXTVAL, SYSDATE, '2020-12', '삼성전자', 'IT/인터넷', '신입', '보통', '합격', 'PT면접', '긍정적', '면접관 다수', '저는 코로나 전 면접을 봤는데, 1차 면접관 4명, 지원자 6명으로 직무, 인성, 각오 등의 면접, 2차 면접관 3면 지원자 6명으로 토론면접. 주제는 랜덤 저희는 <경력> 으로 전 근무지 일에 대해 토론했던 기억이 납니다', '선택한 이유?', '학력, 경력 관한 질문', '상황 대처 질문', '화이팅');


--첨부파일
CREATE TABLE TABLE_REVIEW_BOARD_FILE(
	USER_ID VARCHAR2(100),
	REVIEW_NUM NUMBER(10),
	REVIEW_CNTN_ID NUMBER(20),
	REVIEW_DCMT_RGSR_NO VARCHAR2(30),
	REVIEW_ATCH_FILE_CHING VARCHAR2(300),
	REVIEW_ATCH_DATA_SLP VARCHAR2(500),
	REVIEW_ATCH_ORGN_FILE_NAME VARCHAR2(300),
	REVIEW_ATCH_FILE_SIZE NUMBER(11, 2),
	REVIEW_TRNS_ERR_MSG VARCHAR2(4000),
	CONSTRAINT REVIEW_FILE_PK PRIMARY KEY (REVIEW_CNTN_ID),
	CONSTRAINT REVIEW_FILE_FK FOREIGN KEY (REVIEW_NUM) REFERENCES TABLE_INTERVIEW_REVIEW_BOARD(REVIEW_NUM)
);

SELECT * FROM TABLE_REVIEW_BOARD_FILE;
SELECT * FROM TABLE_INTERVIEW_REVIEW_BOARD;


