CREATE SEQUENCE SENDMESSAGE_NUM_SEQ;
CREATE SEQUENCE RCVMESSAGE_NUM_SEQ;

/*보낸 메세지 함*/
CREATE TABLE TABLE_SEND_MESSAGE(
	MESSAGE_NUM NUMBER(10),
	MESSAGE_SEND_ID VARCHAR2(100),
	MESSAGE_RCV_ID VARCHAR2(100),
	MESSAGE_TITLE VARCHAR2(1000),
	MESSAGE_CONTENT VARCHAR2(3000),
	MESSAGE_DATE DATE,
	CONSTRAINT SENDMESSAGE_SEND_PK PRIMARY KEY(MESSAGE_NUM),
	CONSTRAINT SENDMESSAGE_SEND_ID_FK FOREIGN KEY (MESSAGE_SEND_ID) REFERENCES TABLE_USER(USER_ID),
	CONSTRAINT SENDMESSAGE_RCV_ID_FK FOREIGN KEY (MESSAGE_RCV_ID) REFERENCES TABLE_USER(USER_ID)
);

INSERT INTO TABLE_SEND_MESSAGE
VALUES(MESSAGE_SEQ.NEXTVAL , 'korea5678', 'korea1234' , '안녕하세요. 테스트입니다.' , '테스트 컨텐츠', SYSDATE);

SELECT * FROM (SELECT ROWNUM R, T.* FROM (SELECT * FROM TABLE_SEND_MESSAGE M ORDER BY 1 DESC) T) S
WHERE S.R > 10 AND S.R < 21;

SELECT * FROM TABLE_SEND_MESSAGE;

/*받은 메세지 함*/
CREATE TABLE TABLE_RCV_MESSAGE(
	MESSAGE_NUM NUMBER(10),
	MESSAGE_SEND_ID VARCHAR2(100),
	MESSAGE_RCV_ID VARCHAR2(100),
	MESSAGE_TITLE VARCHAR2(1000),
	MESSAGE_CONTENT VARCHAR2(3000),
	MESSAGE_DATE DATE,
	CONSTRAINT RCVMESSAGE_RCV_PK PRIMARY KEY(MESSAGE_NUM),
	CONSTRAINT RCVMESSAGE_SEND_ID_FK FOREIGN KEY (MESSAGE_SEND_ID) REFERENCES TABLE_USER(USER_ID),
	CONSTRAINT RCVMESSAGE_RCV_ID_FK FOREIGN KEY (MESSAGE_RCV_ID) REFERENCES TABLE_USER(USER_ID)
);

INSERT INTO TABLE_RCV_MESSAGE
VALUES(MESSAGE_NUM_SEQ.NEXTVAL , 'korea1234', 'korea5678' , '안녕하세요. 테스트입니다.' , '테스트 컨텐츠', SYSDATE);

SELECT * FROM (SELECT ROWNUM R, T.* FROM (SELECT * FROM TABLE_RCV_MESSAGE M ORDER BY 1 DESC) T) S
WHERE S.R > 10 AND S.R < 21;

SELECT * FROM TABLE_RCV_MESSAGE;